--- 
- name: Check if the new version exists
  script: ../templates/nexus-install.sh checkNexusInstallation
  register: checkinstallation

- debug: msg="Nexus {{ casfw_nexus_release_version }} already deployed"
  when: checkinstallation.stdout == 'YES'

- debug: msg="Deploying Nexus {{ casfw_nexus_release_version }}"
  when: checkinstallation.stdout == 'NO'

- name: Deploy Nexus
  include: deploy-nexus.yml
  when: checkinstallation.stdout == 'NO'

- name: Final Cleanup
  script: ../templates/nexus-install.sh finalCleanup