--- 
- name: Check if the new version exists
  script: ../templates/hudson-slave-install.sh checkHudsonInstallation
  register: checkinstallation

- debug: msg="Hudson slave {{ casfw_build_release_version }} already deployed"
  when: checkinstallation.stdout == 'YES'

- debug: msg="Deploying Hudson slave {{ casfw_build_release_version }}"
  when: checkinstallation.stdout == 'NO'

- name: Deploy Hudson slave
  include: deploy-hudson-slave.yml
  when: checkinstallation.stdout == 'NO'

- name: Final Cleanup
  script: ../templates/hudson-slave-install.sh finalCleanup