--- 
- name: Check if the new version exists
  script: hudson-slave-install.sh checkHudsonInstallation {{ casfw_home }} {{ hudson_slave_release_version }}
  register: checkinstallation

- debug: msg="Hudson slave {{ hudson_slave_release_version }} already deployed"
  when: checkinstallation.stdout == 'YES'

- debug: msg="Deploying Hudson slave {{ hudson_slave_release_version }}"
  when: checkinstallation.stdout == 'NO'

- name: Deploy Hudson slave
  include: deploy-hudson-slave.yml
  when: checkinstallation.stdout == 'NO'

- name: Final Cleanup
  script: hudson-slave-install.sh finalCleanup {{ casfw_home }} {{ hudson_slave_release_version }}