---
- name: Preparation before install Hudson master
  script: ../templates/hudson-master-install.sh prepareInstallation

- name: Download build-master cdi and install 
  script: ../templates/hudson-master-install.sh downloadCdiInstall

- name: Configure Hudson master
  script: ../templates/hudson-master-install.sh configureHudson

- name: Start Hudson master
  script: ../templates/hudson-master-install.sh startHudson