---  
- name: Check if the new version exists
  script: hudson-master-install.sh checkHudsonInstallation {{ casfw_home }} {{ hudson_master_release_version }}
  register: checkinstallation

- debug: msg="Hudson master {{ hudson_master_release_version }} already deployed"
  when: checkinstallation.stdout == 'YES'

- debug: msg="Deploying Hudson master {{ hudson_master_release_version }}"
  when: checkinstallation.stdout == 'NO'

- name: Deploy Hudson master
  include: deploy-hudson-master.yml
  when: checkinstallation.stdout == 'NO'

- name: Final Cleanup
  script: hudson-master-install.sh finalCleanup {{ casfw_home }} {{ hudson_master_release_version }}