---  
- name: Check if the new version exists
  script: ../templates/hudson-master-install.sh checkHudsonInstallation
  register: checkinstallation
  su: no

- debug: msg="Hudson master {{ casfw_build_release_version }} already deployed"
  when: checkinstallation.stdout == 'YES'

- debug: msg="Deploying Hudson master {{ casfw_build_release_version }}"
  when: checkinstallation.stdout == 'NO'

- name: Deploy Hudson master
  include: deploy-hudson-master.yml
  when: checkinstallation.stdout == 'NO'

- name: Final Cleanup
  script: ../templates/hudson-master-install.sh finalCleanup